### PR TITLE
avoid "sh: next: command not found"

### PR DESCRIPTION
**Pull request by pdurbin**
Saturday's even was great! My first one. Thank you to the organizers!

 @detective-sokka mentioned the website is open source, which is awesome.

This commit is to give new contributors a helping hand.

By the way, https://www.meetup.com/boston-code-and-coffee/ links to https://codeandcoffee.community/ but shouldn't it link to https://www.bostoncodeandcoffee.com ?

### CODE REVIEW

**Comment by detective-sokka** [comment]
Thank you so much for the contribution @pdurbin. That's a great point. I'll inform the social media team

**Review by detective-sokka — APPROVED** [review]

**Comment by alexpereira** [comment]
Hi @pdurbin. Thanks for your contribution!! And sorry for the delay in reviewing your pr. Two things:

1. Can you update the changelog file? This needs to be done for the PR actions to pass.
2. Can you clarify the message you wrote about the links? Are these links referenced in the codebase and they're not working as intended?

**Comment by pdurbin** [comment]
@alexpereira sure, done.

A picture is worth a thousand words, right? I drew a red arrow:

Screenshot 2023-10-09 at 6 11 06 PM

**Comment by alexpereira** [comment]
Ah gotcha.

Hm.. I don't know which link would be best for the meetup page. I'll post this question on Discord and cc you

**Comment by alexpereira** [comment]
I couldn't find you on Discord. But I posted the question.

**Pull request merged**
